// Generated by CoffeeScript 1.10.0
(function() {
  var driver, webdriver;

  webdriver = require('selenium-webdriver');

  driver = (new webdriver.Builder).withCapabilities(webdriver.Capabilities.firefox()).build();

  driver.manage().window().maximize();

  driver.manage().window().setSize(1440, 900);

  driver.get('http://dev-lifelock.samsclub.com/');

  driver.takeScreenshot().then(function(image, err) {
    return require('fs').writeFile('out.png', image, 'base64', function(err) {
      return console.log(err);
    });
  });

  driver.quit();

}).call(this);
