// Generated by CoffeeScript 1.10.0
(function() {
  var driver, files, fs, fsp, resemble, takeScreenshot, webdriver;

  webdriver = require('selenium-webdriver');

  fsp = require('fs-promise');

  fs = require('fs');

  resemble = require('node-resemble.js');

  driver = (new webdriver.Builder).withCapabilities(webdriver.Capabilities.firefox()).build();

  driver.manage().window().maximize();

  driver.manage().window().setSize(1440, 900);

  files = [];

  takeScreenshot = function(url, imageName) {
    driver.get(url);
    return driver.takeScreenshot().then(function(image, err) {
      console.log('write file! ', imageName);
      return fsp.writeFile(imageName, image, 'base64').then(function(err) {
        console.log('done writing: ', imageName);
        return files.push(imageName);
      });
    });
  };

  takeScreenshot('http://dev-lifelock.samsclub.com/', 'dev-lifelock.png').then(function() {
    return takeScreenshot('http://lifelock.samsclub.com/', 'prod.png');
  }).then(function() {
    return resemble(fs.readFileSync(files[0])).compareTo(fs.readFileSync(files[1])).ignoreColors().onComplete(function(data) {
      return console.log(data);
    });
  });

  driver.quit();

}).call(this);
