// Generated by CoffeeScript 1.10.0
(function() {
  var driver, files, fsp, takeScreenshot, webdriver;

  webdriver = require('selenium-webdriver');

  fsp = require('fs-promise');

  driver = (new webdriver.Builder).withCapabilities(webdriver.Capabilities.firefox()).build();

  driver.manage().window().maximize();

  driver.manage().window().setSize(1440, 900);

  files = [];

  takeScreenshot = function(url, imageName) {
    driver.get(url);
    return driver.takeScreenshot().then(function(image, err) {
      console.log('write file! ', imageName);
      return fsp.writeFile(imageName + ".png", image, 'base64').then(function(err) {
        return console.log('done writing: ', imageName);
      });
    });
  };

  takeScreenshot('http://dev-lifelock.samsclub.com/', 'dev-lifelock').then(function() {
    return takeScreenshot('http://lifelock.samsclub.com/', 'prod');
  }).then(function() {
    return console.log('both are done');
  });

  driver.quit();

}).call(this);
